# Generated by Django 4.0.6 on 2022-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofilemodel_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=40, unique=True),
        ),
    ]
