# Generated by Django 4.0.6 on 2022-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofilemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
    ]
